### ISSUE TITLE
Update Button not responding

### ISSUE THREAD

**Issue by sonicpunk** [Jako/ImagePlus#11]
I have just installed the latest version of ImagePlus into a MODX 2.3.3 installation.

When I click on the cropping image, the dialogue box opens, and if I crop something and press update, nothing happens.

**Comment by sonicpunk** [comment]
I get an Uncaught SyntaxError:Unexpected token i in Chrome Dev Tools as error

**Comment by sonicpunk** [comment]
![screen shot 2015-08-18 at 11 10 14](https://cloud.githubusercontent.com/assets/447453/9326402/be0e0e0a-4599-11e5-88df-6586d407a736.png)

**Comment by sonicpunk** [comment]
Could there be a conflict with Content Blocks? I am currently using CB 1.2.6

**Comment by Jako** [comment]
Which MODX thumbnail extra is installed? 

For some reason JSON.stringify(JSON.parse(current), null, '  ') gives an error in imageplus.panel.input.js in line 275. What value is in current? Could you debug that in your installation with Chrome Dev Tools or Firebug?

**Comment by sonicpunk** [comment]
Using pthumb.  current: "industrial close-up 2331262.jpg"

**Comment by sonicpunk** [comment]
If you want to debug, I could give you access to the dev site.....

**Comment by Jako** [comment]
ok. you could contact me on skype: jako.partout

**Comment by mazuhl** [comment]
I was having the same issue and found a work around that might give you a bit of insight into what is causing the problem.

I swapped an existing MODX Image TV over to an Image+ TV. I couldn't get the Image+ TV to save and there wasn't anything showing in the input field. Once I clicked the little "x" icon (which presumably clears the hidden TV fields in the panel) and saved the Resource the Image+ TV worked as expected.

Looks like it was existing TV data causing a problem - probably because the JS expects a JSON reply and it's just getting whatever was in the string. Maybe the Image+ TV needs to be able to say "Not valid JSON? I'll just pretend you returned nothing."

**Comment by Jako** [comment]
This issue is solved in the upcoming 2.4, the original value is retained and transformed into the imagePlus value. With that version you could switch a normal image TV to an Image+ TV retaining the original image. 

The Snippet or TV output code does not respect this at the moment, so the package is not published yet.

A beta with the current state could be found on: http://extras.partout.info/download/imageplus-2.4.0-b1.zip

**Comment by Jako** [comment]
Next beta is available for testing: http://extras.partout.info/download/imageplus-2.4.0-b2.zip

The Snippet and the TV output code work now with a string that points to an image. Switching a normal image TV to an Image+ TV could be done now without hassle.
